---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "afritzler"
    # Ignore K8 packages as these are done manually
    ignore:
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apiextensions-apiserver"
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/apiserver"
      - dependency-name: "k8s.io/client-go"
      - dependency-name: "k8s.io/component-base"
      - dependency-name: "k8s.io/kube-aggregator"
      - dependency-name: "k8s.io/kubectl"
      - dependency-name: "sigs.k8s.io/controller-runtime"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "afritzler"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "afritzler"
