on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

name: Pull Request Code build

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - run: make test
