on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

name: Pull Request Code build

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - run: make test
