on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

name: Pull Request Code build

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.7.0
      env:
        GO111MODULE: "on"
      with:
        args: make build